_target_: unifi3d.models.autoencoders.vqvae_3d.VAE3D
config:
  embed_dim: 3
  n_embed: 8192
  double_z: False
  z_channels: 3
  resolution: 64
  in_channels: 1
  out_ch: 1
  ch: 64
  # ch_mult: !!python/tuple [1,1,2,2,4]  # num_down = len(ch_mult)-1
  ch_mult: [1,2,4]  # num_down = len(ch_mult)-1
  num_res_blocks: 1
  attn_resolutions: []
  dropout: 0.0
  exp_min_threshold: 0.00000001
  exp_max_threshold: 30000
  codebook_weight: 0.1
is_vae: true
