
_target_: unifi3d.models.autoencoders.vqvae_3d.VQVAE
config:
  embed_dim: 3
  n_embed: 8192
  codebook_weight: 1.0
  double_z: False
  z_channels: 3
  resolution: 64
  in_channels: 1
  out_ch: 1
  ch: 64
  # ch_mult: !!python/tuple [1,1,2,2,4]  # num_down = len(ch_mult)-1
  ch_mult: [1,2,4]  # num_down = len(ch_mult)-1
  num_res_blocks: 1
  attn_resolutions: []
  dropout: 0.0
