_target_: unifi3d.models.diffusion.unet_3d.UNet3DModel
dims: 3
image_size: 16 # BS parameter
in_channels: 3 # RGB
out_channels: 3 # RGB
model_channels: 192 # latent channels
num_res_blocks: 2
attention_resolutions: [1, 2, 4] # 16, 8, 4
# note: this isn't actually the resolution but
# the downsampling factor, i.e. this corresnponds to
# attention on spatial resolution 8,16,32, as the
# spatial reolution of the latents is 64 for f4
channel_mult: [ 1,2,4,4 ]
# num_head_channels: 32
num_heads: 6
use_3d_aware_conv: False