#@package _global_

defaults:
  - override /data: sdf # this is used by default
  - override /model: diffusion 
  - override /net_denoise: dit # this is just a placeholder, but actually set by `diff_id`
  - override /net_encode: vae_3d # this is just a placeholder, but actually set by `ae_id`
  - override /diffusion_sampler: ddpm
  - override /metrics: cond_gen_img # or cond_gen_text for text conditioning

overwrite_model_cfg: true

num_samples: 100
num_views_render: 10

num_sampling_steps: 100

ae_id: sdf_ae
diff_id: dit # _unet or _dit
cat_id: "chair"

net_encode:
  ckpt_path: ${paths.shared_ae_checkpoint_folder}/Chair/${ae_id}/model.safetensors

model:
  encoder_decoder: ${net_encode}
  diff_model: ${net_denoise}
  sampling_scheduler: ${diffusion_sampler}

data:
  batch_size: 1
  dataset:
    _target_: unifi3d.data.data_iterators.ShapenetPreprocessedIterator
    path: ${paths.shapenet_preprocessed_dir}
    categories: 
      - ${cat_id}
    mode: "train"
  val_dataset:
    _target_: unifi3d.data.data_iterators.ShapenetPreprocessedIterator
    path: ${paths.shapenet_preprocessed_dir}
    categories: 
      - ${cat_id}
    mode: "val"
  test_dataset:
    _target_: unifi3d.data.data_iterators.ShapenetPreprocessedIterator
    path: ${paths.shapenet_preprocessed_dir}
    categories: 
      - ${cat_id}
    mode: "test"

cond_mode: "image"

compute_metrics: false

ckpt: logs/final_checkpoints_conditional/sdf_ae_dit/model.safetensors

shape: [3, 16, 16, 16]
output_path: logs/final_results_conditional/sdf_ae_dit