- name: "fscore"
  requires_gt: true
  constructor:
    _target_: unifi3d.utils.evaluate.metrics.fscore.FScore
    threshold: 0.05
    num_points: 1000
- name: "chamfer_distance"
  requires_gt: true
  constructor:
    _target_: unifi3d.utils.evaluate.metrics.chamfer_distance.ChamferDistance
    num_points: 1000