# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python scripts/accelerate/acc_train.py hparams_search=diffuse_doctree_unet_vae_optuna_parallel experiment=diffuse_doctree_vae_unet_chair_900

defaults:
  - override /hydra/launcher: ray
  - override /hydra/sweeper: optuna
  - override /logger: null
  - override /data: dualoctree_shape

data:
  train_batch_size: 600
  val_batch_size: ${data.train_batch_size}
  test_batch_size: 1
  data_train:
    dataset:
      num_samples: -1
  data_test:
    dataset:
      num_samples: -1
  data_val:
    dataset:
      num_samples: -1

trainer:
  max_epochs: 100
  min_epochs: 100
  log_every_n_iter: 2
  log_image_every_n_iters: -1 # How often to log images within iterations. Disabled by default (-1).
  check_val_every_n_epoch: 1
  save_checkpoint_every_n_epoch: -1
  ckpt_num: 1
# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged!
optimized_metric: "val_loss"

# Number of GPUs involved in the hyperparameter search
num_parallel_process: 4

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached

  launcher:
    ray:
      init:
        num_gpus: ${num_parallel_process}
        local_mode: False
      remote:
        num_gpus: 1
        max_calls: 1

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: "sdfusion_vqvae"

    # number of parallel workers (i.e. GPUs working in parallel)
    n_jobs: ${num_parallel_process}

    # 'minimize' or 'maximize' the objective
    direction: minimize

    # total number of runs that will be executed
    n_trials: 20

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 12345
      n_startup_trials: 10 # number of random sampling runs before optimization starts

    # define hyperparameter search space
    params:
      model.optimizer.lr: choice(0.0001, 0.001, 0.01, 0.1)
      model.optimizer.weight_decay: choice(0.01, 0.001, 0.0001)
      # data.batch_size: choice(1, 2, 4, 8) # NOTE: Tuning the batch size with TestIterator does not make sense (no variance in batch)
      # model.net.config.dropout: interval(0.0, 0.5)