_target_: unifi3d.trainers.encoder_decoder_trainer.EncoderDecoderTrainer

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.01
loss_requires_grad: false # This will calculate grad even during test and validation set, because dualoctree requires grad to calculate loss. Please set it to False normally.
compile: false

net: ${net_encode}

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 100
  gamma: 0.9
  _partial_: true

loss:
  _target_: unifi3d.losses.autoencoders.vq_loss.VQLoss
  codebook_weight: ${net_encode.config.codebook_weight}
