# https://www.comet.ml

comet:
  _target_: unifi3d.utils.logger.Logger
  config:
    logint: "comet"
    name: ${experiment_name} # any string, set to "default" if not specified
    root_dir: "${paths.output_dir}"
    loggers: ["metric", "image", "hparams"] # "metric", "hparams", "hist", "image", "video", "mesh"
    gpu_summarize": true # Show used / total GPU memory.
    print_every_n_seconds: 1.0 # A Log message is being printed every print_every_n_seconds seconds
    api_key: ${oc.env:COMET_API_TOKEN} # api key is loaded from environment variable
    workspace: "default" 
    tracked_variables: # The keys should match aim/loggers
      metric: ["loss", "lr"]
      image: ["render_gt", "render_rec"]