name: Python style

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: psf/black@stable
        with:
          options: "--check --verbose --diff"
